[package]
name = "wgpu-compute-prime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.3"
pollster = "0.2.5"
wgpu = "0.14.0"
